/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useState } from 'react'
import { useGLTF, useCubeTexture } from '@react-three/drei'
import { events, useFrame, useThree } from "@react-three/fiber";
import { a } from "@react-spring/three";

import deskScene from "../assets/3d/desk.glb";

const Desk = ({ isRotating, setIsRotating, setCurrentStage, setComputerSelection, ...props }) => {
    const deskRef = useRef()
    const { gl, viewport } = useThree();
    const { nodes, materials } = useGLTF(deskScene);
    const lastX = useRef(0);
    const rotationSpeed = useRef(0);
    const dampingFactor = 0.95;

    const handlePointerDown = (e) => {
        e.preventDefault();
        setIsRotating(true);
        const clientX = e.touches ? e.touches[0].clientX : e.clientX;
        lastX.current = clientX;
    }

    const handlePointerUp = (e) => {
        e.preventDefault();
        setIsRotating(false);
    }

    const handlePointerMove = (e) => {
        e.preventDefault();
        if (isRotating) {
            const clientX = e.touches ? e.touches[0].clientX : e.clientX;
            const delta = (clientX - lastX.current) / viewport.width;
            deskRef.current.rotation.y += delta * 0.01 * Math.PI;
            lastX.current = clientX;
            rotationSpeed.current = delta * 0.01 * Math.PI;
        }
    }

    const handleKeyDown = (e) => {
        if (e.key == 'ArrowLeft') {
            if (!isRotating) setIsRotating(true);
            deskRef.current.rotation.y += 0.01 * Math.PI;
        } else if (e.key == 'ArrowRight') {
            if (!isRotating) setIsRotating(true);
            deskRef.current.rotation.y -= 0.01 * Math.PI;
        }
    }

    const handleKeyUp = (e) => {
        if (e.key == 'ArrowLeft' || e.key == 'ArrowRight') {
            setIsRotating(false);
        }
    }

    useFrame(() => {
        if (!isRotating) {
            rotationSpeed.current *= dampingFactor;
            if (Math.abs(rotationSpeed.current) < 0.001) {
                rotationSpeed.current = 0;
            }
            deskRef.current.rotation.y += rotationSpeed.current;
        } else {
            const rotation = deskRef.current.rotation.y;
            const normalizatedRotation = ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);
            //console.log(normalizatedRotation);
            switch (true) {
                case normalizatedRotation >= 5.45 && normalizatedRotation <= 5.85:
                    setCurrentStage(4);// Angular
                    break;
                case normalizatedRotation >= 0.37 && normalizatedRotation <= 0.71:
                    setCurrentStage(3);//HTML CSS y JS
                    break;
                case normalizatedRotation >= 4.44 && normalizatedRotation <= 4.88:
                    setCurrentStage(2);//Three JS
                    break;
                default:
                    setCurrentStage(null);
            }
        }
    })

    useEffect(() => {
        const canvas = gl.domElement;
        canvas.addEventListener('pointerdown', handlePointerDown);
        canvas.addEventListener('pointerup', handlePointerUp);
        canvas.addEventListener('pointermove', handlePointerMove);
        canvas.addEventListener('touchstart', handlePointerDown);
        canvas.addEventListener('touchend', handlePointerUp);
        canvas.addEventListener('touchmove', handlePointerMove);
        document.addEventListener('keydown', handleKeyDown);
        document.addEventListener('keyup', handleKeyUp);
        return () => {
            canvas.removeEventListener('pointerdown', handlePointerDown);
            canvas.removeEventListener('pointerup', handlePointerUp);
            canvas.removeEventListener('pointermove', handlePointerMove);
            canvas.removeEventListener('touchstart', handlePointerDown);
            canvas.removeEventListener('touchend', handlePointerUp);
            canvas.removeEventListener('touchmove', handlePointerMove);
            document.removeEventListener('keydown', handleKeyDown);
            document.removeEventListener('keyup', handleKeyUp);
        }
    }, [gl, handlePointerDown, handlePointerUp, handlePointerMove]);

    const texture = useCubeTexture(
        ['px.jpg', 'nx.jpg', 'py.jpg', 'ny.jpg', 'pz.jpg', 'nz.jpg'],
        { path: 'textures/' }
    );

    const [computerScaleMultiplayer, setComputerScaleMultiplayer] = useState(1);

    return (
        <a.group ref={deskRef} {...props}>
            <group
                onClick={(e) => setComputerSelection(true)}
                onPointerOver={(e) => {
                    if (window.innerWidth < 768) {
                        setComputerSelection(true)
                    }
                    setComputerScaleMultiplayer(1.02);
                }}
                onPointerLeave={(e) => {
                    setComputerScaleMultiplayer(1);
                }}
                name="computer"
                position={[-7.0688, 4.4, -1.0406]}
                rotation={[-Math.PI / 2, 0, 0.716]}
                scale={[0.2334 * computerScaleMultiplayer, 0.2334 * computerScaleMultiplayer, 0.2427 * computerScaleMultiplayer]}
            >
                <group name="VoxRoot">{/* PC */}
                    <group name="VoxTransform">
                        <group name="VoxGroup">
                            <group name="VoxTransform001" position={[0, 0, 20]}>
                                <mesh
                                    name="Object_10"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_10.geometry}
                                    material={materials.VoxMaterial_95}
                                />
                                <mesh
                                    name="Object_11"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_11.geometry}
                                    material={materials.VoxMaterial_96}
                                />
                                <mesh
                                    name="Object_12"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_12.geometry}
                                    material={materials.VoxMaterial_112}
                                />
                                <mesh
                                    name="Object_13"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_13.geometry}
                                    material={materials.VoxMaterial_128}
                                />
                                <mesh
                                    name="Object_14"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_14.geometry}
                                    material={materials.VoxMaterial_136}
                                />
                                <mesh
                                    name="Object_15"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_15.geometry}
                                    material={materials.VoxMaterial_160}
                                />
                                <mesh
                                    name="Object_16"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_16.geometry}
                                    material={materials.VoxMaterial_168}
                                />
                                <mesh
                                    name="Object_5"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_5.geometry}
                                    material={materials.VoxMaterial_64}
                                />
                                <mesh
                                    name="Object_6"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_6.geometry}
                                    material={materials.VoxMaterial_72}
                                />
                                <mesh
                                    name="Object_7"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_7.geometry}
                                    material={materials.VoxMaterial_86}
                                />
                                <mesh
                                    name="Object_8"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_8.geometry}
                                    material={materials.VoxMaterial_87}
                                />
                                <mesh
                                    name="Object_9"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_9.geometry}
                                    material={materials.VoxMaterial_88}
                                />
                            </group>
                        </group>
                    </group>
                </group>
            </group>
            <group
                name="logos"
                position={[3.1094, 14.4349, 10.659]}
                rotation={[-Math.PI / 2, 0, 0.716]}>
                <group name="root">
                    <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
                        <group name="ANDROIDSTUDIO_13" position={[3.2958, 1.264, 0]}>
                            <mesh
                                name="Object_47"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_47.geometry}
                                material={materials.ANDROIDSTUDIO}
                                position={[-6.2624, -6, -18.7025]}
                            />
                        </group>
                        <group name="JAVASCRIPT_5" position={[0.9, -0.5, 4]}>
                            <mesh
                                name="Object_22"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_22.geometry}
                                material={materials.JAVASCRIPT}
                                position={[17.5251, 5, -23.192]}
                                rotation={[0, -0.9, 0]}
                                scale={4.1857}
                            />
                        </group>
                        <group name="UNITY_11" position={[-0.1362, 1.264, 0]}>
                            <mesh
                                name="Object_41"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_41.geometry}
                                material={materials.UNITY}
                                position={[-18.8311, 1, -8.7785]}
                                rotation={[0, 1.4908, 0]}
                                scale={3.5465}
                            />
                        </group>
                        <group name="XCODE_14" position={[5.2343, 1.264, 0]}>
                            <mesh
                                name="Object_50"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_50.geometry}
                                material={materials.XCODE}
                                position={[-6.2624, -6, -18.7025]}
                            />
                        </group>
                    </group>
                </group>
            </group>
            <group
                name="react"
                position={[-32.7485, 19.7949, -10.5488]}
                rotation={[-Math.PI / 2, 0, 1.0788]}
                scale={1.4678}>
                <group
                    name="be9210d376244066bed9d265a7a3a60efbx"
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.01}>
                    <group name="RootNode" position={[-0.0001, 0.0001, -0.0001]}>
                        <group
                            name="React-Logo"
                            position={[-3373.0769, 407.9355, 1457.6678]}
                            rotation={[0, 0.5449, -Math.PI / 2]}
                            scale={[60.6018, 60.6018, 81.5951]}>
                            <mesh
                                name="React-Logo_Material002_0"
                                castShadow
                                receiveShadow
                                geometry={nodes['React-Logo_Material002_0'].geometry}
                                material={materials['Material.002']}
                                position={[9.0888, 38.0794, 14.1326]}
                                rotation={[-0.0635, 0, 0]}
                                scale={0.5845}
                            />
                        </group>
                    </group>
                </group>
            </group>
            <group
                name="css"
                position={[12.6317, 12.8, -13]}
                rotation={[-Math.PI / 2, 0, -2]}
                scale={0.0303}>
                <group name="root001" position={[0.0001, 0, 0]}>
                    <group
                        name="GLTF_SceneRootNode001"
                        position={[0.0001, 0, 0]}
                        rotation={[Math.PI / 2, 0, 0]}>
                        <group
                            name="css_3"
                            position={[20.7893, 136.746, 10.1716]}
                            rotation={[Math.PI / 2, 0, 0]}
                            scale={0.01}>
                            <group
                                name="Cube_1_0"
                                position={[-142.9376, -32.7459, -5922.8745]}
                                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                                scale={100}>
                                <mesh
                                    name="Object_5002"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_5002.geometry}
                                    material={materials['Material.005']}
                                    position={[0, 0, -0.0001]}
                                />
                            </group>
                            <group name="ramka2_2" position={[-182.6805, 35.4909, 1926.6099]}>
                                <mesh
                                    name="Object_10002"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_10002.geometry}
                                    material={materials['Material.004']}
                                    position={[0.007, 0.0026, -0.0034]}
                                />
                            </group>
                            <group name="ramka_1" position={[326.2784, 35.4899, 1926.6099]}>
                                <mesh
                                    name="Object_7001"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_7001.geometry}
                                    material={materials['Material.001']}
                                    position={[0.005, 0.0017, -0.0034]}
                                />
                                <mesh
                                    name="Object_8002"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_8002.geometry}
                                    material={materials['Material.003']}
                                    position={[0.005, 0.0017, -0.0034]}
                                />
                            </group>
                        </group>
                    </group>
                </group>
            </group>
            <group
                name="html5"
                position={[21.7585, 12.9, -13]}
                rotation={[-Math.PI / 2, 0, -2.2109]}
                scale={0.0318}>
                <group name="root002">
                    <group name="GLTF_SceneRootNode002" rotation={[Math.PI / 2, 0, 0]}>
                        <group
                            name="five_2"
                            position={[42.7121, 209.044, 23.5649]}
                            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                            scale={100}>
                            <mesh
                                name="Object_9002"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_9002.geometry}
                                material={materials['Material.012']}
                            />
                        </group>
                        <group
                            name="ramka2_0"
                            position={[18.9625, 117.4799, 10.5265]}
                            rotation={[Math.PI / 2, 0, 0]}
                            scale={0.01}>
                            <mesh
                                name="Object_4001"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_4001.geometry}
                                material={materials['Material.009']}
                                position={[0.0032, -0.0003, 0.0024]}
                            />
                        </group>
                        <group
                            name="ramka_1001"
                            position={[24.052, 117.4799, 10.5265]}
                            rotation={[Math.PI / 2, 0, 0]}
                            scale={0.01}>
                            <mesh
                                name="Object_6002"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_6002.geometry}
                                material={materials['Material.010']}
                                position={[0.0012, -0.0003, 0.0024]}
                            />
                            <mesh
                                name="Object_7002"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_7002.geometry}
                                material={materials['Material.011']}
                                position={[0.0012, -0.0003, 0.0024]}
                            />
                        </group>
                    </group>
                </group>
            </group>
            <group
                name="desk005"
                position={[-5.7897, 0.0755, -6.391]}
                rotation={[-Math.PI / 2, 0, 0.716]}>
                <group name="root003" scale={12.1418}>
                    <group name="GLTF_SceneRootNode003" rotation={[Math.PI / 2, 0, 0]}>
                        <group name="comp_desk_0" rotation={[Math.PI / 2, 0, 0]}>
                            <mesh
                                name="Object_4002"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_4002.geometry}
                                material={materials.comp_desk_c}
                            />
                            <mesh
                                name="Object_5003"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_5003.geometry}
                                material={materials.comp_desk}
                            />
                            <mesh
                                name="Object_6003"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_6003.geometry}
                                material={materials.comp_desk_b}
                            />
                            <mesh
                                name="Object_7003"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_7003.geometry}
                                material={materials.comp_desk_a}
                            />
                        </group>
                        <group name="comp_desk_remote_1" rotation={[Math.PI / 2, 0, 0]}>
                            <mesh
                                name="Object_10003"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_10003.geometry}
                                material={materials.comp_desk_2remote}
                            />
                            <mesh
                                name="Object_11001"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_11001.geometry}
                                material={materials.comp_desk_1remote}
                            />
                            <mesh
                                name="Object_12002"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_12002.geometry}
                                material={materials.comp_desk_button}
                            />
                            <mesh
                                name="Object_9003"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_9003.geometry}
                                material={materials.comp_desk_remote}
                            />
                        </group>
                        <group name="comp_desk_top_2">
                            <mesh
                                name="Object_14002"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_14002.geometry}
                                material={materials.comp_desk_top}
                            />
                        </group>
                    </group>
                </group>
            </group>
            <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
                <group name="Root" position={[1, 0, 0]}>
                    <group
                        name="Camera001"
                        position={[8.4058, 0.2075, 3.1499]}
                        rotation={[-0.1539, 1.3687, 1.7278]}
                    />
                    <group
                        name="Lamp"
                        position={[4.0763, 1.0055, 5.9039]}
                        rotation={[-0.2682, 0.6021, 1.9315]}>
                        <group name="Lamp001" />
                    </group>
                </group>
            </group>
            <group
                name="Sketchfab_model001"
                position={[-4, 14, -8]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={4.3757}>
                <group name="root004">
                    <group name="GLTF_SceneRootNode004" rotation={[Math.PI / 2, 0, 0]}>
                        <group name="rubberduck_0" position={[0, 0.0647, 0]}>
                            <mesh
                                name="Object_4"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_4.geometry}
                                material={materials.rubberduck_clean}
                                position={[0, -0.0457, -0.2285]}
                            />
                        </group>
                    </group>
                </group>
            </group>
            <group
                name="Sketchfab_model002"
                position={[2, 0, 4]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={10.9381}>
                <group name="root005">
                    <group name="GLTF_SceneRootNode005" rotation={[Math.PI / 2, 0, 0]}>
                        <group name="Cylinder002_0">
                            <mesh
                                name="Object_4003"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_4003.geometry}
                                material={materials['01_-_Default']}
                            />
                            <mesh
                                name="Object_5001"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_5001.geometry}
                                material={materials['01_-_Default']}
                            />
                            <mesh
                                name="Object_6001"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_6001.geometry}
                                material={materials['01_-_Default_0']}
                            />
                        </group>
                    </group>
                </group>
            </group>
            <group
                name="Sketchfab_model003"
                position={[-8, 29, -10]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={0.0978}>
                <group name="root006">
                    <group name="GLTF_SceneRootNode006" rotation={[Math.PI / 2, 0, 0]}>
                        <group name="_1">
                            <group name="threejs_0">
                                <mesh
                                    name="Object_5004"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_5004.geometry}
                                    material={materials.material_0}
                                    position={[-132.881, -102.2162, 81.7729]}
                                    rotation={[0, 1.1584, 0]}
                                    scale={0.7307}
                                />
                            </group>
                        </group>
                    </group>
                </group>
            </group>
            <mesh  /* Piso */
                name="Plane"
                castShadow
                receiveShadow
                geometry={nodes.Plane.geometry}
                scale={40.3218}
            >
                <meshBasicMaterial
                    color={materials['Material.007'].color}
                    envMap={texture}
                    reflectivity={0.4}
                />
            </mesh>
            <group name="Mball" position={[0, 25, 90]} scale={32.9905} />
            <mesh
                name="Curve043"
                castShadow
                receiveShadow
                geometry={nodes.Curve043.geometry}
                material={materials['SVGMat.074']}
                position={[-14.4895, 16.0286, -12.543]}
                rotation={[Math.PI / 2, 0, -0.7107]}
                scale={10.9062}
            />
            <mesh
                name="Curve042"
                castShadow
                receiveShadow
                geometry={nodes.Curve042.geometry}
                material={materials['SVGMat.075']}
                position={[-14.962, 16.0841, -13.2712]}
                rotation={[Math.PI / 2, 0, -0.7107]}
                scale={10.9062}
            />
            <mesh
                name="Curve041"
                castShadow
                receiveShadow
                geometry={nodes.Curve041.geometry}
                material={materials['SVGMat.072']}
                position={[-14.9975, 16.0236, -13.3145]}
                rotation={[Math.PI / 2, 0, -0.7107]}
                scale={10.9062}
            />
            <mesh
                name="Curve001"
                castShadow
                receiveShadow
                geometry={nodes.Curve001.geometry}
                material={materials['SVGMat.001']}
                position={[-14.4895, 16.0286, -12.543]}
                rotation={[Math.PI / 2, 0, -0.7107]}
                scale={10.9062}
            />
            <mesh
                name="Curve002"
                castShadow
                receiveShadow
                geometry={nodes.Curve002.geometry}
                material={materials['SVGMat.002']}
                position={[-14.962, 16.0841, -13.2712]}
                rotation={[Math.PI / 2, 0, -0.7107]}
                scale={10.9062}
            />
            <mesh
                name="Curve003"
                castShadow
                receiveShadow
                geometry={nodes.Curve003.geometry}
                material={materials['SVGMat.003']}
                position={[-14.9975, 16.0236, -13.3145]}
                rotation={[Math.PI / 2, 0, -0.7107]}
                scale={10.9062}
            />
        </a.group>
    )
}

export default Desk;