/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: vilmariina (https://sketchfab.com/vilmariina)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/floating-island-of-the-potion-brewer-555992efd5c74cf299f5a3ab4acd0a3b
Title: Floating Island of the Potion Brewer
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { events, useFrame, useThree } from "@react-three/fiber";
import { a } from "@react-spring/three";

import islandScene from "../assets/3d/island.glb";

const Island = ({ isRotating, setIsRotating, setCurrentStage, ...props }) => {
  const islandRef = useRef();
  const { gl, viewport } = useThree();
  const { nodes, materials } = useGLTF(islandScene);
  const lastX = useRef(0);
  const rotationSpeed = useRef(0);
  const dampingFactor = 0.95;

  const handlePointerDown = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(true);
    const clientX = e.touches ? e.touches[0].clientX : e.clientX;
    lastX.current = clientX;
  }

  const handlePointerUp = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(false);
  }

  const handlePointerMove = (e) => {
    e.stopPropagation();
    e.preventDefault();
    if (isRotating) {
      const clientX = e.touches ? e.touches[0].clientX : e.clientX;
      const delta = (clientX - lastX.current) / viewport.width;
      islandRef.current.rotation.y += delta * 0.01 * Math.PI;
      lastX.current = clientX;
      rotationSpeed.current = delta * 0.01 * Math.PI;
    }
  }

  const handleKeyDown = (e) => {
    if (e.key == 'ArrowLeft') {
      if (!isRotating) setIsRotating(true);
      islandRef.current.rotation.y += 0.01 * Math.PI;
    } else if (e.key == 'ArrowRight') {
      if (!isRotating) setIsRotating(true);
      islandRef.current.rotation.y -= 0.01 * Math.PI;
    }
  }

  const handleKeyUp = (e) => {
    if (e.key == 'ArrowLeft' || e.key == 'ArrowRight') {
      setIsRotating(false);
    }
  }

  useFrame(() => {
    if (!isRotating) {
      rotationSpeed.current *= dampingFactor;
      if (Math.abs(rotationSpeed.current) < 0.001) {
        rotationSpeed.current = 0;
      }
      islandRef.current.rotation.y += rotationSpeed.current;
    } else {
      const rotation = islandRef.current.rotation.y;
      const normalizatedRotation = ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);
      switch (true) {
        case normalizatedRotation >= 5.45 && normalizatedRotation <= 5.85:
          setCurrentStage(4);
          break;
        case normalizatedRotation >= 0.85 && normalizatedRotation <= 1.3:
          setCurrentStage(3);
          break;
        case normalizatedRotation >= 2.4 && normalizatedRotation <= 2.6:
          setCurrentStage(2);
          break;
        case normalizatedRotation >= 4.25 && normalizatedRotation <= 4.75:
          setCurrentStage(1);
          break;
        default:
          setCurrentStage(null);
      }
    }
  })

  useEffect(() => {
    const canvas = gl.domElement;
    canvas.addEventListener('pointerdown', handlePointerDown);
    canvas.addEventListener('pointerup', handlePointerUp);
    canvas.addEventListener('pointermove', handlePointerMove);
    document.addEventListener('keydown', handleKeyDown);
    document.addEventListener('keyup', handleKeyUp);
    return () => {
      canvas.removeEventListener('pointerdown', handlePointerDown);
      canvas.removeEventListener('pointerup', handlePointerUp);
      canvas.removeEventListener('pointermove', handlePointerMove);
      document.removeEventListener('keydown', handleKeyDown);
      document.removeEventListener('keyup', handleKeyUp);
    }
  }, [gl, handlePointerDown, handlePointerUp, handlePointerMove])

  return (
    <a.group ref={islandRef} {...props}>
      <group position={[-85.3, -858.2, 387.9]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_48.geometry} material={materials.Bottom_WoodTiling} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.House_Wood_tiling} />
      </group>
      <group position={[-354, 73.8, 593.5]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_54.geometry}
          material={materials.FirewoodRope}
          position={[211.1, 405.9, -70.1]}
        />
      </group>
      <group position={[-388, 43.8, 645.4]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_57.geometry}
          material={materials.Bottles}
          position={[245.1, 457.8, -40.1]}
        />
      </group>
      <group position={[-97.8, 713.2, -182.7]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_60.geometry}
          material={materials.StonesChimney}
          position={[-11, 1.9, -549.2]}
        />
      </group>
      <group position={[-492.7, 27.7, -84.4]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_67.geometry}
          material={materials.CrateBarrel}
          position={[43.4, -133.2, -27.1]}
        />
      </group>
      <group position={[-529.3, 92.3, 380.6]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_74.geometry}
          material={materials.House_Wood_tiling}
          position={[513.7, 238.2, -213.3]}
        />
        <mesh
          geometry={nodes.Object_76.geometry}
          material={materials.FirewoodRope}
          position={[1.2, -20.4, 76.9]}
          rotation={[1.5, 0, 0]}
          scale={0.5}
        />
        <mesh
          geometry={nodes.Object_78.geometry}
          material={materials.PipeLantern}
          position={[0, -26.8, 33.7]}
        />
      </group>
      <group position={[68.5, 195.3, 548.8]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh
          geometry={nodes.Object_81.geometry}
          material={materials.House_Wood_tiling}
          position={[512.9, 235.1, -289.5]}
        />
      </group>
      <group position={[-440.1, 43, -163.3]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_128.geometry}
          material={materials.CrateBarrel}
          position={[0, 0, -42.4]}
        />
      </group>
      <group position={[89.4, 43, 325.1]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_131.geometry}
          material={materials.CrateBarrel}
          position={[0, 0, -42.4]}
        />
      </group>
      <group position={[162.4, 43, 346.3]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_134.geometry}
          material={materials.CrateBarrel}
          position={[0, 0, -42.4]}
        />
      </group>
      <group position={[162.4, 43, -234.2]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_137.geometry}
          material={materials.CrateBarrel}
          position={[0, 0, -42.4]}
        />
      </group>
      <group position={[249.7, 27.7, -84.4]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_140.geometry}
          material={materials.CrateBarrel}
          position={[43.4, -133.2, -27.1]}
        />
      </group>
      <group position={[249.7, 27.7, 16.5]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_143.geometry}
          material={materials.CrateBarrel}
          position={[43.4, -133.2, -27.1]}
        />
      </group>
      <group position={[249.7, 74.8, -17.9]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_146.geometry}
          material={materials.CrateBarrel}
          position={[43.4, -133.2, -27.1]}
        />
      </group>
      <group position={[172.1, 27.7, 536.1]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_155.geometry}
          material={materials.CrateBarrel}
          position={[43.4, -133.2, -27.1]}
        />
      </group>
      <group position={[121.8, 27.7, 527.8]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_158.geometry}
          material={materials.CrateBarrel}
          position={[43.4, -133.2, -27.1]}
        />
      </group>
      <group position={[222.2, 27.7, 532.4]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_161.geometry}
          material={materials.CrateBarrel}
          position={[43.4, -133.2, -27.1]}
        />
      </group>
      <group position={[222.2, 74.7, 537.9]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_164.geometry}
          material={materials.CrateBarrel}
          position={[43.4, -133.2, -27.1]}
        />
      </group>
      <group position={[172.1, 74.7, 532.4]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_167.geometry}
          material={materials.CrateBarrel}
          position={[43.4, -133.2, -27.1]}
        />
      </group>
      <group position={[222.2, 120.3, 532.4]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_170.geometry}
          material={materials.CrateBarrel}
          position={[43.4, -133.2, -27.1]}
        />
      </group>
      <group position={[-423.3, 50.9, 588.1]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_175.geometry}
          material={materials.Bottles}
          position={[280.4, 400.5, -47.3]}
        />
      </group>
      <group position={[-394.6, 50.4, 611.6]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_178.geometry}
          material={materials.Bottles}
          position={[251.7, 424, -46.8]}
        />
      </group>
      <group position={[-390, 88.5, 615.7]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_181.geometry}
          material={materials.FirewoodRope}
          position={[247.1, 428.1, -84.9]}
        />
      </group>
      <group position={[-390, 88.5, 615.7]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_184.geometry}
          material={materials.FirewoodRope}
          position={[247.1, 428.1, -84.9]}
        />
      </group>
      <group position={[85.1, 148.8, 326.2]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_189.geometry}
          material={materials.FirewoodRope}
          position={[-1.6, 23.2, 1.4]}
        />
      </group>
      <group position={[284.2, 43.1, 173.5]} rotation={[-Math.PI / 2, 0, 0.2]} scale={2}>
        <group position={[-1, 14.5, -55.7]}>
          <mesh geometry={nodes.Object_192.geometry} material={materials.SmalLeaves} />
          <mesh geometry={nodes.Object_193.geometry} material={materials.RoundLeaves} />
        </group>
      </group>
      <group position={[79.8, 96.8, 581.7]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_196.geometry}
          material={materials.Bottles}
          position={[251.7, 424, -46.8]}
        />
      </group>
      <group position={[120.4, 120.2, 563.6]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_199.geometry}
          material={materials.FirewoodRope}
          position={[211.1, 405.9, -70.1]}
        />
      </group>
      <group position={[204.6, 50.9, 624]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_202.geometry}
          material={materials.Bottles}
          position={[280.4, 400.5, -47.3]}
        />
      </group>
      <group position={[237.9, 88.5, 651.6]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_205.geometry}
          material={materials.FirewoodRope}
          position={[247.1, 428.1, -84.9]}
        />
      </group>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.House_PlasterWall}
        position={[-36.6, 510.1, 65.8]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.Platform_WoodTiling}
        position={[-13, -121, 123]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials.Balloon}
        position={[-82.6, 0.2, 207]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials.Shed_PlasterWall}
        position={[356.9, 4.7, 468.8]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_12.geometry}
        material={materials.FirewoodRope}
        position={[186, 290.1, 398.1]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_14.geometry}
        material={materials.RoofTiles}
        position={[21.8, 743.8, 282.2]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_16.geometry}
        material={materials.Chimney_PBolts}
        position={[-54.9, 704.6, -179]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_18.geometry}
        material={materials.RoofTiles}
        position={[61.7, 800.1, 100.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_20.geometry}
        material={materials.House_Wood_tiling}
        position={[9.2, 214.7, 209.3]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_22.geometry}
        material={materials.DoorsAndDoorframes}
        position={[-51.6, 97.3, 189]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_24.geometry}
        material={materials.WindowGlass}
        position={[9.2, 213.8, 209.3]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_26.geometry}
        material={materials.RoofMaterial}
        position={[9.2, 214.7, 209.3]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_28.geometry}
        material={materials.Grass_base}
        position={[-13, -121, 123]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_30.geometry}
        material={materials.Material_5}
        position={[356.9, 4.7, 468.8]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_32.geometry}
        material={materials.Shed_Wood_Tiling}
        position={[86, 9.3, 551.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_34.geometry}
        material={materials.Test_Wood}
        position={[-422.9, 24.2, 588.3]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_36.geometry}
        material={materials.stoneHighlights}
        position={[-195, 212.2, -143.5]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_38.geometry}
        material={materials.stone_wall}
        position={[-198.5, 119.8, -190.4]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_40.geometry}
        material={materials.Groundrocks}
        position={[-100, 8.8, 258.3]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_42.geometry}
        material={materials.ClothesPipeWater}
        position={[180, 258.9, 474]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_44.geometry}
        material={materials.FirewoodRope}
        position={[-82.6, 0.2, 207]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_46.geometry}
        material={materials.CrateBarrel}
        position={[-88.8, -314.9, 796.3]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_51.geometry}
        material={materials.FirewoodRope}
        position={[-661.7, -435.5, 389.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_62.geometry}
        material={materials.Smoke_Chimney}
        position={[-181.1, 908.7, -224.9]}
        rotation={[0, -0.6, 0]}
      />
      <mesh
        geometry={nodes.Object_64.geometry}
        material={materials.ClothesPipeWater}
        position={[-360.4, -786.8, -121.8]}
        rotation={[-2.2, 0, 3.1]}
      />
      <mesh
        geometry={nodes.Object_69.geometry}
        material={materials.CabinGlass}
        position={[-81.7, -888.7, 224.2]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_71.geometry}
        material={materials.grasstuft}
        position={[-37.1, 10.3, 661.8]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_83.geometry}
        material={materials.PipeLantern}
        position={[38.6, 162, 547.9]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.8}
      />
      <mesh
        geometry={nodes.Object_85.geometry}
        material={materials.FirewoodRope}
        position={[45, 196, 549.1]}
        rotation={[-Math.PI / 2, -1.5, -Math.PI / 2]}
        scale={0.5}
      />
      <mesh
        geometry={nodes.Object_87.geometry}
        material={materials.FirewoodRope}
        position={[-185.9, -766, 407.5]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_89.geometry}
        material={materials.House_Wood_tiling}
        position={[-169.6, -766.7, 390.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_91.geometry}
        material={materials.PipeLantern}
        position={[-191.3, -809.1, 411.2]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_93.geometry}
        material={materials.PipeLantern}
        position={[-544, -613.1, 342]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_95.geometry}
        material={materials.FirewoodRope}
        position={[-538, -570, 339.3]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_97.geometry}
        material={materials.BottomCabins}
        position={[-415.7, -686.7, 225.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_99.geometry}
        material={materials.PipeLantern}
        position={[32.5, 381.8, 221]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_101.geometry}
        material={materials.FirewoodRope}
        position={[33.7, 415.7, 214.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_103.geometry}
        material={materials.House_Wood_tiling}
        position={[33.3, 415, 191.1]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_105.geometry}
        material={materials.House_Wood_tiling}
        position={[-173.4, 415, 136.4]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_107.geometry}
        material={materials.PipeLantern}
        position={[-203.3, 381.8, 135.5]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_109.geometry}
        material={materials.FirewoodRope}
        position={[-196.9, 415.7, 136.8]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_111.geometry}
        material={materials.FirewoodRope}
        position={[-63.6, 3.7, 89.1]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_113.geometry}
        material={materials.House_Wood_tiling}
        position={[-175.3, 203.6, -151.7]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_115.geometry}
        material={materials.FirewoodRope}
        position={[-198.8, 204.3, -151.3]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_117.geometry}
        material={materials.PipeLantern}
        position={[-205.2, 170.3, -152.6]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_119.geometry}
        material={materials.House_Wood_tiling}
        position={[9, 208.5, 224.3]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_121.geometry}
        material={materials.PipeLantern}
        position={[8.1, 175.2, 254.2]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_123.geometry}
        material={materials.FirewoodRope}
        position={[9.3, 209.2, 247.8]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_125.geometry}
        material={materials.House_Wood_tiling}
        position={[-85.3, -858.2, 387.9]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_148.geometry}
        material={materials.CrateBarrel}
        position={[-143.3, 74.8, 635]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_150.geometry}
        material={materials.CrateBarrel}
        position={[-118.9, 27.7, 652.1]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_152.geometry}
        material={materials.CrateBarrel}
        position={[-166.8, 27.7, 647.5]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_172.geometry}
        material={materials.Chimney_PBolts}
        position={[-76.6, -876.8, 588.8]}
        rotation={[0, 0, -Math.PI / 4]}
        scale={0.6}
      />
      <mesh
        geometry={nodes.Object_186.geometry}
        material={materials.Bottles}
        position={[85.1, 114.2, 326.9]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </a.group>
  )
}


export default Island;